### ISSUE TITLE
Use of `__VA_OPT__` function macro

### ISSUE THREAD

**Issue by jserv** [RinHizakura/mini-gdbstub#2]
C++20 introduces the `__VA_OPT__` function macro, which is also available in GNU C and GNU C++. However, for older versions of clang, `__VA_OPT__` might be absent. Tested on macOS Catalina:
```
cc -c -Iinclude -Wall -Wextra -MMD -Werror -O3 ./lib/conn.c -o /Users/apple/rv/rv32emu/build/mini-gdbstub//conn.o
./lib/conn.c:40:9: error: expected ')'
        warn("Set sockopt fail.\n");
        ^
include/utils/log.h:21:28: note: expanded from macro 'warn'
           strerror(errno) __VA_OPT__(, ) __VA_ARGS__)
                           ^
./lib/conn.c:40:9: note: to match this '('
include/utils/log.h:20:11: note: expanded from macro 'warn'
    __info(YELLOW "ERRNO: %s\n" NC format, \
          ^
./lib/conn.c:49:9: error: expected ')'
        warn("Bind fail.\n");
        ^
```

We shall avoid such new features.

Reference: https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

**Comment by RinHizakura** [comment]
So sad :(

This is fixed in [895ac33](https://github.com/RinHizakura/mini-gdbstub/commit/895ac336deeb06938717e3fde64914372dd3ca89) now, which simply the debug util to avoid `__VA_OPT__`
