### ISSUE TITLE
The link of the introduction is dead

### ISSUE THREAD

**Issue by exeex** [RinHizakura/mini-gdbstub#4]
Hi,

Thanks for your contribution, the tutorial is helpful for me. 👍 

I read the introduction two weeks ago. However, that is dead now.

https://[www.chciken.com](https://www.chciken.com/tlmboy/2022/04/03/gdb-z80.html)/tlmboy/2022/04/03/gdb-z80.html

Will you publish the introduction in any other place? Thanks a lot!

**Comment by RinHizakura** [comment]
It's a bad news that the website is shut down for some reason.  But the article is not written by me. I just share it for someone who would like to learn more about this project.

Maybe you could reach the author directly here If you want to know what's happen there: https://github.com/not-chciken

**Comment by RinHizakura** [comment]
Looks like the link is available now! I'll close the issue.
